version: "3"
services:
  app:
    container_name: chat-server
    restart: always
    build: .
    ports:
      - 5500:5500
    expose:
      - 5500
    networks:
      - some-net
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - some-net
networks:
  some-net:
    driver: bridge