version: '3.3'

services:
  web:
    build: ./
    command: sh -c "python stod/manage.py makemigrations groups posts tags && python stod/manage.py migrate && PYTHONPATH=`pwd`/stod/ gunicorn stod.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
      - 1338:443
    depends_on: 
      - web
    volumes:
      - ./nginx/certs:/etc/nginx/certs
volumes:
  postgres_data:
