version: "3"

services:
  db:
    image: spartakode/sqlite3:latest
    volumes:
      - ./database.db:/db/db.db
  web:
    environment:
      - DATABASE_NAME=‘django_db'
      - DATABASE_USER=‘admin’
      - DATABASE_PASSWORD=‘Gobbbledygook!1’
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
