version: '3.3'

services:
  web:
    build: ./
    command: sh -c "python stod/manage.py makemigrations groups posts tags && python stod/manage.py migrate && PYTHONPATH=`pwd`/stod/ gunicorn stod.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 80:80
    depends_on: 
      - web
    volumes:
      - /etc/letsencrypt/live/stodbackend.app/fullchain.pem:/etc/letsencrypt/live/stodbackend.app/fullchain.pem
      - /etc/letsencrypt/live/stodbackend.app/privkey.pem:/etc/letsencrypt/live/stodbackend.app/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
volumes:
  postgres_data:
