version: "3.3"

services:
  web:
    build: ./
    command: sh -c "python stod/manage.py makemigrations && python stod/manage.py migrate && python stod/manage.py runserver 0.0.0.0:8000"

    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
volumes:
  postgres_data:
