# Generated by Django 3.1.2 on 2020-11-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.CharField(max_length=25),
        ),
    ]
