# Generated by Django 3.1.2 on 2020-11-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201119_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.CharField(max_length=50),
        ),
    ]
